spring:
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      uri: http://localhost:8999
      fail-fast: true
      retry:
        initial-interval: 1000
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 7000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.batch_size: 45
        order_inserts: true
        order_updates: true
        jdbc.fetch_size: 1000
        jdbc.batch_versioned_data: true

database:
  url: jdbc:postgresql://host.docker.internal:5432/csp_dev?useSSL=false
  username: postgres
  password: postgres
  hikari-properties:
    autoCommit: false
    poolName: csp_pool
    maxPoolSize: 20
    maxIdleTime: 10000
    
jwt.secret: itsasecret

eureka:
  client:
#    eureka-server-port: 8998
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8998/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2